apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argo-beta.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "argo-beta.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "argo-beta.fullname" . }}
  strategy:
    type: {{ .Values.strategy.type }}
    {{- if eq .Values.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
    {{- end }}
  template:
    metadata:
      labels:
        app: {{ include "argo-beta.fullname" . }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: ubuntu
        image: "{{ .Values.images.ubuntu.repository }}:{{ .Values.images.ubuntu.tag }}"
        imagePullPolicy: {{ .Values.images.ubuntu.pullPolicy }}
        command: ["sleep", "604800"]
        volumeMounts:
        - mountPath: /data
          name: test-vol

      - name: nginx-sidecar
        image: "{{ .Values.images.nginx.repository }}:{{ .Values.images.nginx.tag }}"
        imagePullPolicy: {{ .Values.images.nginx.pullPolicy }}
        volumeMounts:
        - mountPath: /data
          name: test-vol

      volumes:
      - name: test-vol
        persistentVolumeClaim:
          claimName: {{ .Values.volumes.pvc.claimName }}